config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'games#index'

  get '/start', to: 'games#start'
  get '/battle', to: 'games#battle'

  resources :braves, only: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brave.rb
class Brave < ApplicationRecord


  belongs_to :user, dependent: :destroy

  validates :user_id, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 10 }
  # 十文字以内
  validates :exp, presence: true
  validates :level, presence: true
  validates :max_hp, presence: true
  validates :offense, presence: true
  validates :defense, presence: true

  # 戦闘中に使用するゲッター・セッターを追加
  attr_accessor :hp, :damage

  # sessionに保存するデータ（戦闘中に必要となるデータ）を作成するメソッド
  # hp は戦闘時の変化に対応できるよう，引数で与えられるようにしておく。
  def session_attributes(hp: self.max_hp)
    attributes.slice('name', 'offense', 'defense').merge('hp' => hp)
  end

  include Calculation
  # モジュールにいれていく？


  def attack(monster)
    monster.hp -= monster.damage = damage_calc(attacker: self, defender: monster)
    # HPが0以下にならないようにする
    monster.hp = 0 if monster.hp < 0
  end

  def lose_exp(monster_exp)
    # 経験値を減少
    self.exp -= monster_exp / 2
    # 経験値がマイナスにならないようにする
    self.exp = 0 if self.exp < 0
  end

  def current_level
    level = ExpTable.where('exp > ?', self.exp).minimum(:level)
    # レベルが最大を超えたとき（level が nil のとき）の対処をしておく
    level.present? ? level : ExpTable.maximum(:level) + 1
  end

  def status_up(level_up_times)
    level_up_times.times do
      # ステータスアップ量にはランダム性を入れる
      self.max_hp += brave_status_up(self.level)
      self.offense += brave_status_up(self.level)
      self.defense += brave_status_up(self.level)
      self.level += 1
    end
  end
end

app/models/exp_table.rb
class ExpTable < ApplicationRecord
  validates :level, presence: true, uniqueness: true
  validates :exp, presence: true
end

app/models/monster.rb
class Monster < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image, presence: true
  validates :recommended_level, presence: true
  validates :max_hp, presence: true
  validates :offense, presence: true
  validates :defense, presence: true
  validates :exp, presence: true

  attr_accessor :hp, :damage

  # sessionに保存するデータ（戦闘中に必要となるデータ）を作成するメソッド
  def session_attributes
    attributes.slice('name', 'offense', 'defense', 'exp').merge('hp' => self.max_hp)
  end

  include Calculation

  def attack(brave)
    brave.hp -= brave.damage = damage_calc(attacker: self, defender: brave)
    # HPが0以下にならないようにする
    brave.hp = 0 if brave.hp < 0
  end

end

app/models/user.rb
class User < ApplicationRecord

  # ユーザーが作成されたときに作動
  after_create :create_initial_setting

  # Brave クラスとは 1:1 の関係
  has_one :brave, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # ユーザーが作成されたときに，動作するメソッド
  def create_initial_setting
    # has_one の場合は，user.brave.create という書き方ではなく user.create_brave という書き方になる
    create_brave!(default_brave_params)
  end

  private

  # 勇者の初期ステータス
  def default_brave_params
    {
      name: 'ゆうしゃ',
      exp: 0,
      level: 1,
      max_hp: 15,
      offense: 10,
      defense: 10
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 全ページをログイン必須とする
  before_action :authenticate_user!
end

app/controllers/braves_controller.rb
class BravesController < ApplicationController
  def update
    @brave = current_user.brave
    @brave.update!(brave_params)
  end

  private

  def brave_params
    params.require(:brave).permit(:name)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @brave = current_user.brave
    @monster = Monster.where('recommended_level <= ?', @brave.level).sample
    session[:brave] = @brave.session_attributes
    session[:monster] = @monster.session_attributes
  end

  def start
    @brave = current_user.brave
    @monster = Monster.find_by(name: session[:monster]['name'])
    session[:brave] = @brave.session_attributes
    session[:monster] = @monster.session_attributes
  end

  def battle
    battle_start

    if @monster.hp <= 0
      # モンスターを倒した場合
      victory_reward
      reappear_monster
    elsif @brave.hp <= 0
      # 勇者が倒れた場合
      defeat_processing
      reappear_monster
    end

    p @all_messages = all_messages

  end
end

private

  def battle_start

    @brave = Brave.new(session[:brave])
    @monster = Monster.new(session[:monster])
    @brave.attack(@monster)
    session[:monster]['hp'] = @monster.hp
    @monster_damage_messages = Message.damage(attacker: @brave, defender: @monster)
    if @monster.hp.positive?
    @monster.attack(@brave)
    session[:brave]['hp'] = @brave.hp
    @brave_damage_messages = Message.damage(attacker: @monster, defender: @brave)
    end

    battle_info
  end

  def victory_reward
    # データを最新にしてから処理を行う
    @brave = current_user.brave
    # 経験値を追加
    @brave.exp += session[:monster]['exp']
     # レベルアップしているか判定し，レベルアップしているときはステータスをアップさせ，メッセージを作成する
     level_up_times = @brave.current_level - @brave.level
     if level_up_times > 0
       @brave.status_up(level_up_times)
       @level_up_messages = Message.level_up(@brave)
     end
    @victory_messages = Message.victory(@monster)
  end

  def defeat_processing
    @brave = current_user.brave
    @brave.lose_exp(session[:monster]['exp'])
    @defeat_messages = Message.defeat(@brave)
  end

  def reappear_monster
    @brave.save
    @monster = Monster.where('recommended_level <= ?', @brave.level).sample
    session[:monster] = @monster.session_attributes
  end

  def all_messages
    [
    @monster_damage_messages,
    @brave_damage_messages,
    @victory_messages,
    @defeat_messages
    ].flatten.compact
  end

  # ターミナルで一旦確認できるように
  def battle_info
    puts <<~TEXT
      ========================================
      勇者の攻撃力: #{@brave.offense}
      モンスターの防御力: #{@monster.defense}

      モンスターの受けたダメージ: #{@monster.damage}
      モンスターの残りHP: #{@monster.hp} 
      ----------------------------------------
      モンスターの攻撃力： #{@monster.offense}
      勇者の防御力： #{@brave.defense}

      勇者の受けたダメージ: #{@brave.damage}
      勇者の残りHP： #{@brave.hp} 
      ========================================
    TEXT
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/braves/_body.html.erb
<%= form_with model: @brave do |form| %>
  <div class="form-group">
    <%= form.label :name, class: 'control-label' %>（１０文字以内）
    <%= form.text_field :name, class: 'form-control', required: true, maxlength: '10' %>
  </div>

  <div class="form-group">
    <%= form.submit '名前を変更する', class: 'btn btn-black btn-block' %>
  </div>
<% end %>

app/views/braves/_footer.html.erb
<%= link_to 'アカウント編集', edit_user_registration_path, class: 'btn btn-black btn-block' %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-black btn-block' %>

app/views/braves/_modal.html.erb
<div class="modal fade" id="edit-modal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="change-name-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content game-container text-center">
      <div class="modal-header">
        <h5 class="modal-title" id="change-name-label">設定</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <hr class="game-line">
      <div class="modal-body">
        <%= render 'braves/body' %>
      </div>
      <hr class="game-line">
      <div class="modal-footer">
        <%= render 'braves/footer' %>
      </div>
    </div>
  </div>
</div>

app/views/braves/update.js.erb
// トップページの勇者名を変更
document.getElementById('top-brave-name').innerText = "<%= @brave.name %>"
// モーダルを閉じる
$('#edit-modal').modal('hide')

// トップページの勇者名を変更
document.getElementById('top-brave-name').innerText = "<%= @brave.name %>"
// ********** 以下を追加 **********
// 戦闘ページの勇者名を変更
document.getElementById('battle-brave-name').innerText = "<%= @brave.name %>"
// ********** 以上を追加 **********
// モーダルを閉じる
$('#edit-modal').modal('hide')

app/views/games/battle.js.erb
var MONSTER_DAMAGE_LENGTH = <%= @monster_damage_messages.length %>
// メッセージが nil の場合には 0 が代入されるようにしておく
var BRAVE_DAMAGE_LENGTH = <%= @brave_damage_messages&.length || 0 %>
var VICTORY_LENGTH = <%= @victory_messages&.length || 0 %>
var DEFEAT_LENGTH = <%= @defeat_messages&.length || 0 %>

// メッセージ総数
var ALL_LENGTH = <%= @all_messages.length %>

// Rubyの配列をJSの配列に変換
var allMessages = <%= raw @all_messages.to_json %>

// タイマー用
var count = 0
var timer
// メッセージ送りの間隔（単位はミリ秒）
var timeout = 500

var flashingTimer
var monsterReceivedDamage = function () {
    if (count === MONSTER_DAMAGE_LENGTH - 1) {
        // モンスターを50ミリ秒ごとに点滅
        flashingTimer = setInterval(function () {
            battleMonsterImage.style.opacity ^= '1'
        }, 50)
    } else if (count === MONSTER_DAMAGE_LENGTH) {
        // 点滅を解除して表示状態に
        clearInterval(flashingTimer)
        battleMonsterImage.style.opacity = '1'
    }
}

var braveReceivedDamage = function () {
    
    if (count === MONSTER_DAMAGE_LENGTH + BRAVE_DAMAGE_LENGTH - 1) {
        // 勇者がダメージを受けたときに戦闘画面のHP表示を更新
        document.getElementById('battle-hp').innerText = "<%= session[:brave]['hp'] %>"
        // 画面を揺らす
        battleBody.classList.add('swing')
        timeout = 1000
    } else if (count == MONSTER_DAMAGE_LENGTH + BRAVE_DAMAGE_LENGTH) {
        // 画面を揺れを無しにする
        battleBody.classList.remove('swing')
    }


    if (count === MONSTER_DAMAGE_LENGTH + BRAVE_DAMAGE_LENGTH - 1) {
        // 勇者がダメージを受けたときに戦闘画面のHP表示を更新
        document.getElementById('battle-hp').innerText = "<%= session[:brave]['hp'] %>"
        timeout = 1000
    }
}

var continueBattle = function () {
    if (count === ALL_LENGTH) {
        // 戦闘画面の「たたかう」ボタンを表示
        battleMessages.innerHTML = ''
        battleButtonContainer.style.display = 'block'
    }
}

<% if @victory_messages.present? || @defeat_messages.present? %>
var disappearMonster = function () {
    if (count === MONSTER_DAMAGE_LENGTH + BRAVE_DAMAGE_LENGTH) {
        // モンスターの文字と画像を非表示にする
        battleMonster.style.opacity = '0'
        timeout = 1500
    }
}

var reappearMonster = function () {
    if (count === ALL_LENGTH) {
         // トップページのステータスを更新
        document.getElementById('top-status').innerHTML = "<%= j(render 'games/status/top_status') %>"
        // トップページのモンスターを更新
        document.getElementById('top-monster-name').innerText = '<%= @monster.name %>'
        document.getElementById('top-monster-image').innerHTML = "<%= j(render 'games/monster/image') %>"
        // モーダルを閉じる
        $('#battle-modal').modal('hide')
    }
}
<% end %>

var putsMessage = function () {
    if (count < ALL_LENGTH) {
        // メッセージ出力は共通処理としておく。
        battleMessages.insertAdjacentHTML('beforeend', '<p>' + allMessages[count] + '</p>')
    }
}

var messageFeed = function () {

      monsterReceivedDamage()

   if (VICTORY_LENGTH > 0) {
        // 勝利した場合
        disappearMonster()
        reappearMonster()
    } else if (DEFEAT_LENGTH > 0) {
        // 敗北した場合
        braveReceivedDamage()
        if (count === MONSTER_DAMAGE_LENGTH + BRAVE_DAMAGE_LENGTH - 1) timeout = 2000
        reappearMonster()
    } else {
        // 戦闘が継続する場合
        braveReceivedDamage()
        continueBattle()
    }
    
    putsMessage()

    count++
    // timeout 秒後に messageFeed() を動作
    // （自分自身の関数を呼び出すことで繰り返し処理を実現している）
    timer = setTimeout(messageFeed, timeout)
    // ループ処理を終了させる
    if (count > ALL_LENGTH) clearTimeout(timer)
}

// メッセージ送りなどを作動
messageFeed()

app/views/games/battle/_modal.html.erb
<div class="modal fade" id="battle-modal" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content game-container">
      <div class="modal-body mt-4" id="battle-body">
        <%= render 'games/status/battle' %>
        <%= render 'games/monster/battle' %>
        <%= render 'games/message/battle' %>
      </div>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<%# 3グロック＋２モーダル %>

<%# ステータタスブロック %>

<div class="game-font">
  <%= render 'braves/modal' %>
  <%= render 'games/battle/modal' %>
  <%= render 'games/status/top' %>
  <%= render 'games/monster/top' %>
  <%= render 'games/message/top' %>
</div>

app/views/games/message/_battle.html.erb
<div class="game-container message-container mb-5">
  <div class="px-4 py-3 battle-message-container">
    <div id="battle-messages">
      <%= Message.start(@monster) %>
    </div>
    <div class="mt-4" id="battle-button-container">
      <%= button_to 'たたかう', battle_path, class: 'btn btn-black btn-block', id: 'battle-button', remote: true, method: :get %>
    </div>
  </div>
</div>

app/views/games/message/_top.html.erb
<div class="game-container message-container mb-5">
  <div class="px-4 py-3">
    <div class="my-2">
      <%= button_to 'たたかう！', start_path, class: 'btn btn-black btn-block', remote: true, method: :get, data: { toggle: 'modal', target: '#battle-modal' } %>
    </div>
  </div>
  <hr class="game-line">
  <div class="px-4 py-3">
    <button type="button" class="btn btn-black btn-block my-2" data-toggle="modal" data-target="#edit-modal">
      設定
    </button>
  </div>
</div>

app/views/games/monster/_battle.html.erb
<div class="py-4 text-center" id="battle-monster">
  <p id="battle-monster-name">
    <%= @monster.name %>
  </p>
  <div id="battle-monster-image">
    <%= render 'games/monster/image' %>
  </div>
</div>

app/views/games/monster/_image.html.erb
<%= image_tag "monsters/#{@monster.image}", alt: @monster.name, height: '150' %>

app/views/games/monster/_top.html.erb
<div class="py-4 text-center" id="top-monster">
  <p id="top-monster-name">
    <%= @monster.name %>
  </p>
  <div id="top-monster-image">
    <%= render 'games/monster/image' %>
  </div>
</div>

app/views/games/start.js.erb
// バトル画面のステータスを更新
document.getElementById('battle-status').innerHTML = "<%= j(render 'games/status/battle_status') %>"
// バトル画面のモンスターを更新
document.getElementById('battle-monster-name').innerText = '<%= @monster.name %>'
battleMonsterImage.innerHTML = "<%= j(render 'games/monster/image') %>"
// モンスターを表示
battleMonster.style.opacity = '1'
// バトル画面のメッセージ欄を更新
battleMessages.innerHTML = "<%= Message.start(@monster) %>"
battleButtonContainer.style.display = 'block'

app/views/games/status/_battle.html.erb
<div class="game-container status-container">
  <p class="game-label" id="battle-brave-name"><%= @brave.name %></p>
  <div class="game-content">
    <div class="row justify-content-between no-gutters" id="battle-status">
      <%= render 'games/status/battle_status' %>
    </div>
  </div>
</div>

app/views/games/status/_battle_status.html.erb
<div class="col-5">
  <span>LV</span>
  <span class="float-right" id="battle-level"><%= @brave.level %></span>
</div>
<div class="col-5">
  <span>HP</span>
  <%# HPが変化するように %>
  <span class="float-right" id="battle-hp"><%= session[:brave]['hp'] %></span>
</div>

app/views/games/status/_top.html.erb
<div class="game-container status-container">
  <p class="game-label" id="top-brave-name"><%= @brave.name %></p>
  <div class="game-content">
    <div class="row justify-content-between no-gutters" id="top-status">
      <%= render 'games/status/top_status' %>
    </div>
  </div>
</div>

app/views/games/status/_top_status.html.erb
<div class="col-5">
  <span>LV</span>
  <span class="float-right"><%= @brave.level %></span>
</div>
<div class="col-5">
  <span>HP</span>
  <span class="float-right"><%= @brave.max_hp %></span>
</div>
<div class="col-5">
  <span>攻</span>
  <span class="float-right"><%= @brave.offense %></span>
</div>
<div class="col-5">
  <span>防</span>
  <span class="float-right"><%= @brave.defense %></span>
</div>
<div class="col-12">
  <span>EXP</span>
  <span class="float-right"><%= @brave.exp %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ドラクエ風Railsアプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- 全ページにナビバーを追加 -->
    <%= render 'shared/header' %>

    
    <div class="base-container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <span class="navbar-brand">ドラクエ風ゲーム Rails版</span>
    <% unless user_signed_in? %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>